_target_: epochalyst.pipeline.model.model.ModelPipeline
_convert_: partial

x_sys:
  _target_: epochalyst.pipeline.model.transformation.transformation.TransformationPipeline

y_sys:
  _target_: epochalyst.pipeline.model.transformation.transformation.TransformationPipeline

train_sys:
  _target_: epochalyst.pipeline.model.training.training.TrainingPipeline

pred_sys:
  _target_: epochalyst.pipeline.model.transformation.transformation.TransformationPipeline

label_sys:
  _target_: epochalyst.pipeline.model.transformation.transformation.TransformationPipeline
