defaults:
  - base_cv
  - hydra/logging
  - model: gru_simple
  - wandb: train

metadata_path: data/raw/train.csv
eeg_path: data/raw/train_eegs
spectrogram_path: data/raw/train_spectrograms
raw_path: data/raw
cache_path: data/cache
processed_path: data/processed

scorer:
  _target_: src.scoring.kldiv.KLDiv
cache_size: -1
splitter:
  'stratified_splitter'
allow_multiple_instances: True
