defaults:
  - base_cv
  - hydra/logging
  - model: gru_simple
  - wandb: train

raw_data_path: data/...
raw_target_path: data/...
metadata_path: data/...
scorer:
  _target_: src.scoring.kldiv.KLDiv
cache_size: -1
splitter:
  # To be implemented
allow_multiple_instances: True
