defaults:
  - base_cv
  - hydra/logging
  - model: gru_simple
  - wandb: train

raw_path: data/raw/
cache_path: data/cache
processed_path: data/processed

scorer:
  _target_: src.scoring.kldiv.KLDiv
cache_size: -1
splitter:
  # To be implemented
allow_multiple_instances: True
