defaults:
  - base_cv
  - hydra/logging
  - model: jaspers_eeg_net_dont_touch
  - wandb: train

metadata_path: data/raw/train.csv
eeg_path: data/raw/train_eegs
spectrogram_path: data/raw/train_spectrograms
raw_path: data/raw
cache_path: data/cache
processed_path: data/processed

scorer:
  _target_: src.scoring.kldiv.KLDiv
  voter_threshold: 9
cache_size: -1
splitter:
  _target_: src.utils.stratified_splitter.StratifiedSplitter
  n_splits: 5
allow_multiple_instances: true
save_folds: true
