defaults:
  - base_train
  - hydra/logging
  - model: cnn1d
  - wandb: train

metadata_path: data/raw/train.csv
eeg_path: data/raw/train_eegs
spectrogram_path: data/raw/train_spectrograms

scorer:
  _target_: src.scoring.kldiv.KLDiv
test_size: 0.2
cache_size: -1
allow_multiple_instances: false
