defaults:
  - base_train
  - hydra/logging
  - model: cnn2d_timm_eeg
  - wandb: train

raw_path: data/raw
cache_path: data/cache
processed_path: data/processed

scorer:
  _target_: src.scoring.kldiv.KLDiv
test_size: 0.2
cache_size: -1
splitter:
  'stratified_splitter'
allow_multiple_instances: true
