defaults:
  - base_train
  - hydra/logging
  - model: gru_simple
  - wandb: train

raw_path: data/raw/
scorer:
  _target_: src.scoring.kldiv.KLDiv
test_size: 0.2
cache_size: -1
allow_multiple_instances: false
