defaults:
  - base_train
  - hydra/logging
  - model: test
  - wandb: train

raw_data_path: data/...
raw_target_path: data/...
scorer:
  _target_: src.scoring.dice_coefficient.DiceCoefficient
test_size: 0
cache_size: -1
allow_multiple_instances: false
