defaults:
  - base_train
  - hydra/logging
  - model: cnn1d
  - wandb: train


raw_path: data/raw/
scorer:
  _target_: src.scoring.dice_coefficient.DiceCoefficient
test_size: 0
cache_size: -1
allow_multiple_instances: false
