defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps:
    - _target_: src.modules.transformation.eeg.clip.ClipEEG
      lower: -1024
      upper: 1024
    - _target_: src.modules.transformation.nantozero.NaNToZero
      eeg: true
    - _target_: src.modules.transformation.eeg.divide.Divide
      value: 32
    - _target_: src.modules.transformation.eeg.butter.ButterFilter

y_sys:
  steps:
    - _target_: src.modules.transformation.target.sum_to_one.SumToOne

train_sys:
  steps:
    - _target_: src.modules.training.main_trainer.MainTrainer
      model_name: EEGNet # Can't have special characters or spaces
      model:
        _target_: src.modules.training.models.eeg_net.EEGNet
        num_classes: 6
        in_channels: 20
        kernels: [3,5,7,9]
      optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.Adam
        lr: 0.001
      criterion:
        _target_: src.modules.training.losses.kldiv.CustomKLDivLoss
        reduction: "batchmean"
      epochs: 20
      batch_size: 64
      patience: 10
      dataset:
        _target_: src.modules.training.datasets.main_dataset.MainDataset
        data_type: "eeg"
        augmentations:
          _target_: torch_audiomentations.Compose
          transforms:
            - _target_: torch_audiomentations.AddColoredNoise
              p: 0.15
              mode: "per_channel"
              p_mode: "per_channel"
              max_snr_in_db: 15
              sample_rate: 200
