defaults:
  - /model/parallel-data-cv370@steps.0
  - /model/indigo-pike-cv380@steps.1
  - /model/tender-cycle-cv382@steps.2
  - /model/icy-azimuth-cv384@steps.3

_target_: src.modules.training.base_ensembling.BaseEnsemble
_convert_: partial
