defaults:
  - /model/wise_men_multi_res_bi_gru@steps.0
  - /model/wise_men_mrbg_circumferential@steps.1 
  - /model/dark-audience@steps.2
  - /model/wise_men_regular_temple@steps.3
  - /model/wise_men_circumferential@steps.4
  - /model/dark-audience@steps.5
  - /model/brown-fjord@steps.6
_target_: src.modules.training.base_ensembling.BaseEnsemble
_convert_: partial
